#!/bin/csh
setenv CLASSPATH ../jars/Jeli.jar:./Jeli.jar
set TO  = "-u"
if ("$1" == "-w") then
   set TO  = "-w"
endif
java Jeli.ConvertFile $TO ringconfig ChainOfProcesses FanOfProcesses TreeOfProcesses RingOfProcesses
chmod 755 runring
